environment:
  APPVEYOR_CACHE_SKIP_RESTORE: true

version: 5.0.1.{build}

install:
  - ps: Install-Product node 10
  - npx lerna bootstrap

cache:
  - '%APPDATA%\npm-cache'

before_build:
  - npm run lint
  - npm run test

build_script:
  - npm run build

artifacts:
  - path: out\*.exe
  - path: out\*.yml

branches:
  except:
    - i18n
